// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: build_keys_private.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const deleteBuildKeyPrivate = `-- name: DeleteBuildKeyPrivate :exec
DELETE FROM build_keys_private WHERE key_id = $1
`

func (q *Queries) DeleteBuildKeyPrivate(ctx context.Context, keyID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteBuildKeyPrivate, keyID)
	return err
}

const getBuildKeyPrivate = `-- name: GetBuildKeyPrivate :one
SELECT key_id, encrypted_key, encryption_algo, created_at
FROM build_keys_private
WHERE key_id = $1
`

func (q *Queries) GetBuildKeyPrivate(ctx context.Context, keyID uuid.UUID) (BuildKeysPrivate, error) {
	row := q.db.QueryRow(ctx, getBuildKeyPrivate, keyID)
	var i BuildKeysPrivate
	err := row.Scan(
		&i.KeyID,
		&i.EncryptedKey,
		&i.EncryptionAlgo,
		&i.CreatedAt,
	)
	return i, err
}

const storeBuildKeyPrivate = `-- name: StoreBuildKeyPrivate :exec
INSERT INTO build_keys_private (key_id, encrypted_key, encryption_algo)
VALUES ($1, $2, $3)
`

type StoreBuildKeyPrivateParams struct {
	KeyID          uuid.UUID `json:"key_id"`
	EncryptedKey   []byte    `json:"encrypted_key"`
	EncryptionAlgo string    `json:"encryption_algo"`
}

func (q *Queries) StoreBuildKeyPrivate(ctx context.Context, arg StoreBuildKeyPrivateParams) error {
	_, err := q.db.Exec(ctx, storeBuildKeyPrivate, arg.KeyID, arg.EncryptedKey, arg.EncryptionAlgo)
	return err
}
