// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: builds.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countBuilds = `-- name: CountBuilds :one
SELECT count(*) FROM builds
WHERE ($1::build_status IS NULL OR status = $1::build_status)
`

func (q *Queries) CountBuilds(ctx context.Context, status NullBuildStatus) (int64, error) {
	row := q.db.QueryRow(ctx, countBuilds, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBuild = `-- name: CreateBuild :one
INSERT INTO builds (name, created_by)
VALUES ($1, $2)
RETURNING id, name, status, created_by, created_at, finalized_at, contract_hash, contract_yaml, is_immutable
`

type CreateBuildParams struct {
	Name      string    `json:"name"`
	CreatedBy uuid.UUID `json:"created_by"`
}

func (q *Queries) CreateBuild(ctx context.Context, arg CreateBuildParams) (Build, error) {
	row := q.db.QueryRow(ctx, createBuild, arg.Name, arg.CreatedBy)
	var i Build
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.FinalizedAt,
		&i.ContractHash,
		&i.ContractYaml,
		&i.IsImmutable,
	)
	return i, err
}

const finalizeBuild = `-- name: FinalizeBuild :exec
UPDATE builds
SET status = 'FINALIZED',
    contract_yaml = $2,
    contract_hash = $3,
    finalized_at = now(),
    is_immutable = true
WHERE id = $1
`

type FinalizeBuildParams struct {
	ID           uuid.UUID `json:"id"`
	ContractYaml *string   `json:"contract_yaml"`
	ContractHash *string   `json:"contract_hash"`
}

func (q *Queries) FinalizeBuild(ctx context.Context, arg FinalizeBuildParams) error {
	_, err := q.db.Exec(ctx, finalizeBuild, arg.ID, arg.ContractYaml, arg.ContractHash)
	return err
}

const getBuildByID = `-- name: GetBuildByID :one
SELECT id, name, status, created_by, created_at, finalized_at, contract_hash, contract_yaml, is_immutable
FROM builds
WHERE id = $1
`

func (q *Queries) GetBuildByID(ctx context.Context, id uuid.UUID) (Build, error) {
	row := q.db.QueryRow(ctx, getBuildByID, id)
	var i Build
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.FinalizedAt,
		&i.ContractHash,
		&i.ContractYaml,
		&i.IsImmutable,
	)
	return i, err
}

const listBuilds = `-- name: ListBuilds :many
SELECT id, name, status, created_by, created_at, finalized_at, contract_hash, is_immutable
FROM builds
WHERE ($3::build_status IS NULL OR status = $3::build_status)
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListBuildsParams struct {
	Limit  int32           `json:"limit"`
	Offset int32           `json:"offset"`
	Status NullBuildStatus `json:"status"`
}

type ListBuildsRow struct {
	ID           uuid.UUID          `json:"id"`
	Name         string             `json:"name"`
	Status       string             `json:"status"`
	CreatedBy    uuid.UUID          `json:"created_by"`
	CreatedAt    time.Time          `json:"created_at"`
	FinalizedAt  pgtype.Timestamptz `json:"finalized_at"`
	ContractHash *string            `json:"contract_hash"`
	IsImmutable  bool               `json:"is_immutable"`
}

func (q *Queries) ListBuilds(ctx context.Context, arg ListBuildsParams) ([]ListBuildsRow, error) {
	rows, err := q.db.Query(ctx, listBuilds, arg.Limit, arg.Offset, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBuildsRow{}
	for rows.Next() {
		var i ListBuildsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.FinalizedAt,
			&i.ContractHash,
			&i.IsImmutable,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBuildStatus = `-- name: UpdateBuildStatus :exec
UPDATE builds SET status = $2 WHERE id = $1
`

type UpdateBuildStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateBuildStatus(ctx context.Context, arg UpdateBuildStatusParams) error {
	_, err := q.db.Exec(ctx, updateBuildStatus, arg.ID, arg.Status)
	return err
}
