// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: build_sections.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const createBuildSection = `-- name: CreateBuildSection :one
INSERT INTO build_sections (build_id, persona_role, submitted_by, encrypted_payload, encrypted_symmetric_key, section_hash, signature)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, build_id, persona_role, submitted_by, encrypted_payload, encrypted_symmetric_key, section_hash, signature, submitted_at
`

type CreateBuildSectionParams struct {
	BuildID               uuid.UUID `json:"build_id"`
	PersonaRole           string    `json:"persona_role"`
	SubmittedBy           uuid.UUID `json:"submitted_by"`
	EncryptedPayload      string    `json:"encrypted_payload"`
	EncryptedSymmetricKey *string   `json:"encrypted_symmetric_key"`
	SectionHash           string    `json:"section_hash"`
	Signature             string    `json:"signature"`
}

func (q *Queries) CreateBuildSection(ctx context.Context, arg CreateBuildSectionParams) (BuildSection, error) {
	row := q.db.QueryRow(ctx, createBuildSection,
		arg.BuildID,
		arg.PersonaRole,
		arg.SubmittedBy,
		arg.EncryptedPayload,
		arg.EncryptedSymmetricKey,
		arg.SectionHash,
		arg.Signature,
	)
	var i BuildSection
	err := row.Scan(
		&i.ID,
		&i.BuildID,
		&i.PersonaRole,
		&i.SubmittedBy,
		&i.EncryptedPayload,
		&i.EncryptedSymmetricKey,
		&i.SectionHash,
		&i.Signature,
		&i.SubmittedAt,
	)
	return i, err
}

const getBuildSectionByRole = `-- name: GetBuildSectionByRole :one
SELECT id, build_id, persona_role, submitted_by, encrypted_payload, encrypted_symmetric_key, section_hash, signature, submitted_at
FROM build_sections
WHERE build_id = $1 AND persona_role = $2
`

type GetBuildSectionByRoleParams struct {
	BuildID     uuid.UUID `json:"build_id"`
	PersonaRole string    `json:"persona_role"`
}

func (q *Queries) GetBuildSectionByRole(ctx context.Context, arg GetBuildSectionByRoleParams) (BuildSection, error) {
	row := q.db.QueryRow(ctx, getBuildSectionByRole, arg.BuildID, arg.PersonaRole)
	var i BuildSection
	err := row.Scan(
		&i.ID,
		&i.BuildID,
		&i.PersonaRole,
		&i.SubmittedBy,
		&i.EncryptedPayload,
		&i.EncryptedSymmetricKey,
		&i.SectionHash,
		&i.Signature,
		&i.SubmittedAt,
	)
	return i, err
}

const getBuildSectionsByBuildID = `-- name: GetBuildSectionsByBuildID :many
SELECT id, build_id, persona_role, submitted_by, encrypted_payload, encrypted_symmetric_key, section_hash, signature, submitted_at
FROM build_sections
WHERE build_id = $1
ORDER BY submitted_at ASC
`

func (q *Queries) GetBuildSectionsByBuildID(ctx context.Context, buildID uuid.UUID) ([]BuildSection, error) {
	rows, err := q.db.Query(ctx, getBuildSectionsByBuildID, buildID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BuildSection{}
	for rows.Next() {
		var i BuildSection
		if err := rows.Scan(
			&i.ID,
			&i.BuildID,
			&i.PersonaRole,
			&i.SubmittedBy,
			&i.EncryptedPayload,
			&i.EncryptedSymmetricKey,
			&i.SectionHash,
			&i.Signature,
			&i.SubmittedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
