// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: build_assignments.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const checkUserAssignedToBuild = `-- name: CheckUserAssignedToBuild :one
SELECT EXISTS(
    SELECT 1 FROM build_assignments
    WHERE build_id = $1 AND user_id = $2 AND role_id = $3
) as is_assigned
`

type CheckUserAssignedToBuildParams struct {
	BuildID uuid.UUID `json:"build_id"`
	UserID  uuid.UUID `json:"user_id"`
	RoleID  uuid.UUID `json:"role_id"`
}

func (q *Queries) CheckUserAssignedToBuild(ctx context.Context, arg CheckUserAssignedToBuildParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkUserAssignedToBuild, arg.BuildID, arg.UserID, arg.RoleID)
	var is_assigned bool
	err := row.Scan(&is_assigned)
	return is_assigned, err
}

const createBuildAssignment = `-- name: CreateBuildAssignment :one
INSERT INTO build_assignments (
    build_id,
    role_id,
    user_id,
    assigned_by
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, build_id, role_id, user_id, assigned_by, assigned_at
`

type CreateBuildAssignmentParams struct {
	BuildID    uuid.UUID `json:"build_id"`
	RoleID     uuid.UUID `json:"role_id"`
	UserID     uuid.UUID `json:"user_id"`
	AssignedBy uuid.UUID `json:"assigned_by"`
}

func (q *Queries) CreateBuildAssignment(ctx context.Context, arg CreateBuildAssignmentParams) (BuildAssignment, error) {
	row := q.db.QueryRow(ctx, createBuildAssignment,
		arg.BuildID,
		arg.RoleID,
		arg.UserID,
		arg.AssignedBy,
	)
	var i BuildAssignment
	err := row.Scan(
		&i.ID,
		&i.BuildID,
		&i.RoleID,
		&i.UserID,
		&i.AssignedBy,
		&i.AssignedAt,
	)
	return i, err
}

const deleteBuildAssignmentsByBuildID = `-- name: DeleteBuildAssignmentsByBuildID :exec
DELETE FROM build_assignments
WHERE build_id = $1
`

func (q *Queries) DeleteBuildAssignmentsByBuildID(ctx context.Context, buildID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteBuildAssignmentsByBuildID, buildID)
	return err
}

const getBuildAssignmentByBuildAndRole = `-- name: GetBuildAssignmentByBuildAndRole :one
SELECT ba.id, ba.build_id, ba.role_id, ba.user_id, ba.assigned_by, ba.assigned_at, r.name as role_name, u.name as user_name, u.email as user_email
FROM build_assignments ba
JOIN roles r ON ba.role_id = r.id
JOIN users u ON ba.user_id = u.id
WHERE ba.build_id = $1 AND ba.role_id = $2
LIMIT 1
`

type GetBuildAssignmentByBuildAndRoleParams struct {
	BuildID uuid.UUID `json:"build_id"`
	RoleID  uuid.UUID `json:"role_id"`
}

type GetBuildAssignmentByBuildAndRoleRow struct {
	ID         uuid.UUID `json:"id"`
	BuildID    uuid.UUID `json:"build_id"`
	RoleID     uuid.UUID `json:"role_id"`
	UserID     uuid.UUID `json:"user_id"`
	AssignedBy uuid.UUID `json:"assigned_by"`
	AssignedAt time.Time `json:"assigned_at"`
	RoleName   string    `json:"role_name"`
	UserName   string    `json:"user_name"`
	UserEmail  string    `json:"user_email"`
}

func (q *Queries) GetBuildAssignmentByBuildAndRole(ctx context.Context, arg GetBuildAssignmentByBuildAndRoleParams) (GetBuildAssignmentByBuildAndRoleRow, error) {
	row := q.db.QueryRow(ctx, getBuildAssignmentByBuildAndRole, arg.BuildID, arg.RoleID)
	var i GetBuildAssignmentByBuildAndRoleRow
	err := row.Scan(
		&i.ID,
		&i.BuildID,
		&i.RoleID,
		&i.UserID,
		&i.AssignedBy,
		&i.AssignedAt,
		&i.RoleName,
		&i.UserName,
		&i.UserEmail,
	)
	return i, err
}

const getBuildAssignmentsByBuildID = `-- name: GetBuildAssignmentsByBuildID :many
SELECT ba.id, ba.build_id, ba.role_id, ba.user_id, ba.assigned_by, ba.assigned_at, r.name as role_name, u.name as user_name, u.email as user_email
FROM build_assignments ba
JOIN roles r ON ba.role_id = r.id
JOIN users u ON ba.user_id = u.id
WHERE ba.build_id = $1
ORDER BY r.name
`

type GetBuildAssignmentsByBuildIDRow struct {
	ID         uuid.UUID `json:"id"`
	BuildID    uuid.UUID `json:"build_id"`
	RoleID     uuid.UUID `json:"role_id"`
	UserID     uuid.UUID `json:"user_id"`
	AssignedBy uuid.UUID `json:"assigned_by"`
	AssignedAt time.Time `json:"assigned_at"`
	RoleName   string    `json:"role_name"`
	UserName   string    `json:"user_name"`
	UserEmail  string    `json:"user_email"`
}

func (q *Queries) GetBuildAssignmentsByBuildID(ctx context.Context, buildID uuid.UUID) ([]GetBuildAssignmentsByBuildIDRow, error) {
	rows, err := q.db.Query(ctx, getBuildAssignmentsByBuildID, buildID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetBuildAssignmentsByBuildIDRow{}
	for rows.Next() {
		var i GetBuildAssignmentsByBuildIDRow
		if err := rows.Scan(
			&i.ID,
			&i.BuildID,
			&i.RoleID,
			&i.UserID,
			&i.AssignedBy,
			&i.AssignedAt,
			&i.RoleName,
			&i.UserName,
			&i.UserEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBuildAssignmentsByUserID = `-- name: GetBuildAssignmentsByUserID :many
SELECT ba.id, ba.build_id, ba.role_id, ba.user_id, ba.assigned_by, ba.assigned_at, r.name as role_name, b.name as build_name, b.status as build_status
FROM build_assignments ba
JOIN roles r ON ba.role_id = r.id
JOIN builds b ON ba.build_id = b.id
WHERE ba.user_id = $1
ORDER BY ba.assigned_at DESC
`

type GetBuildAssignmentsByUserIDRow struct {
	ID          uuid.UUID `json:"id"`
	BuildID     uuid.UUID `json:"build_id"`
	RoleID      uuid.UUID `json:"role_id"`
	UserID      uuid.UUID `json:"user_id"`
	AssignedBy  uuid.UUID `json:"assigned_by"`
	AssignedAt  time.Time `json:"assigned_at"`
	RoleName    string    `json:"role_name"`
	BuildName   string    `json:"build_name"`
	BuildStatus string    `json:"build_status"`
}

func (q *Queries) GetBuildAssignmentsByUserID(ctx context.Context, userID uuid.UUID) ([]GetBuildAssignmentsByUserIDRow, error) {
	rows, err := q.db.Query(ctx, getBuildAssignmentsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetBuildAssignmentsByUserIDRow{}
	for rows.Next() {
		var i GetBuildAssignmentsByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.BuildID,
			&i.RoleID,
			&i.UserID,
			&i.AssignedBy,
			&i.AssignedAt,
			&i.RoleName,
			&i.BuildName,
			&i.BuildStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
