// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"net/netip"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditEventType string

const (
	AuditEventTypeBUILDCREATED          AuditEventType = "BUILD_CREATED"
	AuditEventTypeWORKLOADSUBMITTED     AuditEventType = "WORKLOAD_SUBMITTED"
	AuditEventTypeENVIRONMENTSTAGED     AuditEventType = "ENVIRONMENT_STAGED"
	AuditEventTypeAUDITORKEYSREGISTERED AuditEventType = "AUDITOR_KEYS_REGISTERED"
	AuditEventTypeCONTRACTASSEMBLED     AuditEventType = "CONTRACT_ASSEMBLED"
	AuditEventTypeBUILDFINALIZED        AuditEventType = "BUILD_FINALIZED"
	AuditEventTypeBUILDCANCELLED        AuditEventType = "BUILD_CANCELLED"
	AuditEventTypeUSERCREATED           AuditEventType = "USER_CREATED"
	AuditEventTypeROLEASSIGNED          AuditEventType = "ROLE_ASSIGNED"
	AuditEventTypeTOKENCREATED          AuditEventType = "TOKEN_CREATED"
	AuditEventTypeTOKENREVOKED          AuditEventType = "TOKEN_REVOKED"
	AuditEventTypeCONTRACTDOWNLOADED    AuditEventType = "CONTRACT_DOWNLOADED"
)

func (e *AuditEventType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AuditEventType(s)
	case string:
		*e = AuditEventType(s)
	default:
		return fmt.Errorf("unsupported scan type for AuditEventType: %T", src)
	}
	return nil
}

type NullAuditEventType struct {
	AuditEventType AuditEventType `json:"audit_event_type"`
	Valid          bool           `json:"valid"` // Valid is true if AuditEventType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAuditEventType) Scan(value interface{}) error {
	if value == nil {
		ns.AuditEventType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AuditEventType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAuditEventType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AuditEventType), nil
}

type BuildStatus string

const (
	BuildStatusCREATED               BuildStatus = "CREATED"
	BuildStatusWORKLOADSUBMITTED     BuildStatus = "WORKLOAD_SUBMITTED"
	BuildStatusENVIRONMENTSTAGED     BuildStatus = "ENVIRONMENT_STAGED"
	BuildStatusAUDITORKEYSREGISTERED BuildStatus = "AUDITOR_KEYS_REGISTERED"
	BuildStatusCONTRACTASSEMBLED     BuildStatus = "CONTRACT_ASSEMBLED"
	BuildStatusFINALIZED             BuildStatus = "FINALIZED"
	BuildStatusCANCELLED             BuildStatus = "CANCELLED"
)

func (e *BuildStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = BuildStatus(s)
	case string:
		*e = BuildStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for BuildStatus: %T", src)
	}
	return nil
}

type NullBuildStatus struct {
	BuildStatus BuildStatus `json:"build_status"`
	Valid       bool        `json:"valid"` // Valid is true if BuildStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBuildStatus) Scan(value interface{}) error {
	if value == nil {
		ns.BuildStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.BuildStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBuildStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.BuildStatus), nil
}

type PersonaRole string

const (
	PersonaRoleSOLUTIONPROVIDER PersonaRole = "SOLUTION_PROVIDER"
	PersonaRoleDATAOWNER        PersonaRole = "DATA_OWNER"
	PersonaRoleAUDITOR          PersonaRole = "AUDITOR"
	PersonaRoleENVOPERATOR      PersonaRole = "ENV_OPERATOR"
	PersonaRoleADMIN            PersonaRole = "ADMIN"
	PersonaRoleVIEWER           PersonaRole = "VIEWER"
)

func (e *PersonaRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PersonaRole(s)
	case string:
		*e = PersonaRole(s)
	default:
		return fmt.Errorf("unsupported scan type for PersonaRole: %T", src)
	}
	return nil
}

type NullPersonaRole struct {
	PersonaRole PersonaRole `json:"persona_role"`
	Valid       bool        `json:"valid"` // Valid is true if PersonaRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPersonaRole) Scan(value interface{}) error {
	if value == nil {
		ns.PersonaRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PersonaRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPersonaRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PersonaRole), nil
}

type ApiToken struct {
	ID         uuid.UUID          `json:"id"`
	UserID     uuid.UUID          `json:"user_id"`
	Name       string             `json:"name"`
	TokenHash  string             `json:"token_hash"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt  time.Time          `json:"created_at"`
}

type AuditEvent struct {
	ID                uuid.UUID       `json:"id"`
	BuildID           uuid.UUID       `json:"build_id"`
	SequenceNo        int32           `json:"sequence_no"`
	EventType         string          `json:"event_type"`
	ActorUserID       uuid.UUID       `json:"actor_user_id"`
	ActorPublicKey    *string         `json:"actor_public_key"`
	IpAddress         *netip.Addr     `json:"ip_address"`
	DeviceMetadata    []byte          `json:"device_metadata"`
	EventData         json.RawMessage `json:"event_data"`
	PreviousEventHash string          `json:"previous_event_hash"`
	EventHash         string          `json:"event_hash"`
	Signature         *string         `json:"signature"`
	CreatedAt         time.Time       `json:"created_at"`
}

type Build struct {
	ID           uuid.UUID          `json:"id"`
	Name         string             `json:"name"`
	Status       string             `json:"status"`
	CreatedBy    uuid.UUID          `json:"created_by"`
	CreatedAt    time.Time          `json:"created_at"`
	FinalizedAt  pgtype.Timestamptz `json:"finalized_at"`
	ContractHash *string            `json:"contract_hash"`
	ContractYaml *string            `json:"contract_yaml"`
	IsImmutable  bool               `json:"is_immutable"`
}

type BuildSection struct {
	ID                    uuid.UUID `json:"id"`
	BuildID               uuid.UUID `json:"build_id"`
	PersonaRole           string    `json:"persona_role"`
	SubmittedBy           uuid.UUID `json:"submitted_by"`
	EncryptedPayload      string    `json:"encrypted_payload"`
	EncryptedSymmetricKey *string   `json:"encrypted_symmetric_key"`
	SectionHash           string    `json:"section_hash"`
	Signature             string    `json:"signature"`
	SubmittedAt           time.Time `json:"submitted_at"`
}

type User struct {
	ID           uuid.UUID `json:"id"`
	Name         string    `json:"name"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	IsActive     bool      `json:"is_active"`
	CreatedAt    time.Time `json:"created_at"`
}

type UserRole struct {
	ID         uuid.UUID `json:"id"`
	UserID     uuid.UUID `json:"user_id"`
	Role       string    `json:"role"`
	AssignedBy uuid.UUID `json:"assigned_by"`
	AssignedAt time.Time `json:"assigned_at"`
}
