// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AssignRole(ctx context.Context, arg AssignRoleParams) (UserRole, error)
	CountAuditEventsByBuildID(ctx context.Context, buildID uuid.UUID) (int64, error)
	CountBuilds(ctx context.Context, status NullBuildStatus) (int64, error)
	CreateAPIToken(ctx context.Context, arg CreateAPITokenParams) (CreateAPITokenRow, error)
	CreateAuditEvent(ctx context.Context, arg CreateAuditEventParams) (AuditEvent, error)
	CreateBuild(ctx context.Context, arg CreateBuildParams) (Build, error)
	CreateBuildSection(ctx context.Context, arg CreateBuildSectionParams) (BuildSection, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	DeactivateUser(ctx context.Context, id uuid.UUID) error
	DeleteRolesByUserID(ctx context.Context, userID uuid.UUID) error
	FinalizeBuild(ctx context.Context, arg FinalizeBuildParams) error
	GetAPITokenByHash(ctx context.Context, tokenHash string) (ApiToken, error)
	GetAuditEventsByBuildID(ctx context.Context, buildID uuid.UUID) ([]AuditEvent, error)
	GetBuildByID(ctx context.Context, id uuid.UUID) (Build, error)
	GetBuildSectionByRole(ctx context.Context, arg GetBuildSectionByRoleParams) (BuildSection, error)
	GetBuildSectionsByBuildID(ctx context.Context, buildID uuid.UUID) ([]BuildSection, error)
	GetLatestAuditEvent(ctx context.Context, buildID uuid.UUID) (AuditEvent, error)
	GetRolesByUserID(ctx context.Context, userID uuid.UUID) ([]UserRole, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	ListAPITokensByUserID(ctx context.Context, userID uuid.UUID) ([]ListAPITokensByUserIDRow, error)
	ListBuilds(ctx context.Context, arg ListBuildsParams) ([]ListBuildsRow, error)
	ListUsers(ctx context.Context) ([]ListUsersRow, error)
	RevokeAPIToken(ctx context.Context, arg RevokeAPITokenParams) error
	UpdateBuildStatus(ctx context.Context, arg UpdateBuildStatusParams) error
	UpdateTokenLastUsed(ctx context.Context, id uuid.UUID) error
}

var _ Querier = (*Queries)(nil)
