// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: system_logs.sql

package repository

import (
	"context"
)

const createSystemLog = `-- name: CreateSystemLog :one
INSERT INTO system_logs (actor_email, action, resource, ip_address, status, details)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, timestamp, actor_email, action, resource, ip_address, status, details
`

type CreateSystemLogParams struct {
	ActorEmail string  `json:"actor_email"`
	Action     string  `json:"action"`
	Resource   string  `json:"resource"`
	IpAddress  string  `json:"ip_address"`
	Status     string  `json:"status"`
	Details    *string `json:"details"`
}

func (q *Queries) CreateSystemLog(ctx context.Context, arg CreateSystemLogParams) (SystemLog, error) {
	row := q.db.QueryRow(ctx, createSystemLog,
		arg.ActorEmail,
		arg.Action,
		arg.Resource,
		arg.IpAddress,
		arg.Status,
		arg.Details,
	)
	var i SystemLog
	err := row.Scan(
		&i.ID,
		&i.Timestamp,
		&i.ActorEmail,
		&i.Action,
		&i.Resource,
		&i.IpAddress,
		&i.Status,
		&i.Details,
	)
	return i, err
}

const listSystemLogs = `-- name: ListSystemLogs :many
SELECT id, timestamp, actor_email, action, resource, ip_address, status, details
FROM system_logs
ORDER BY timestamp DESC
LIMIT $1 OFFSET $2
`

type ListSystemLogsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListSystemLogs(ctx context.Context, arg ListSystemLogsParams) ([]SystemLog, error) {
	rows, err := q.db.Query(ctx, listSystemLogs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SystemLog{}
	for rows.Next() {
		var i SystemLog
		if err := rows.Scan(
			&i.ID,
			&i.Timestamp,
			&i.ActorEmail,
			&i.Action,
			&i.Resource,
			&i.IpAddress,
			&i.Status,
			&i.Details,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
