// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: users.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (name, email, password_hash)
VALUES ($1, $2, $3)
RETURNING id, name, email, is_active, created_at, must_change_password, password_changed_at
`

type CreateUserParams struct {
	Name         string `json:"name"`
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
}

type CreateUserRow struct {
	ID                 uuid.UUID          `json:"id"`
	Name               string             `json:"name"`
	Email              string             `json:"email"`
	IsActive           bool               `json:"is_active"`
	CreatedAt          time.Time          `json:"created_at"`
	MustChangePassword bool               `json:"must_change_password"`
	PasswordChangedAt  pgtype.Timestamptz `json:"password_changed_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Name, arg.Email, arg.PasswordHash)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.IsActive,
		&i.CreatedAt,
		&i.MustChangePassword,
		&i.PasswordChangedAt,
	)
	return i, err
}

const deactivateUser = `-- name: DeactivateUser :exec
UPDATE users SET is_active = false WHERE id = $1
`

func (q *Queries) DeactivateUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deactivateUser, id)
	return err
}

const forcePasswordChange = `-- name: ForcePasswordChange :exec
UPDATE users
SET must_change_password = true
WHERE id = $1
`

func (q *Queries) ForcePasswordChange(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, forcePasswordChange, id)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT u.id, u.name, u.email, u.password_hash, u.is_active, u.created_at,
       u.public_key, u.public_key_fingerprint, u.public_key_registered_at, u.public_key_expires_at,
       u.must_change_password, u.password_changed_at
FROM users u
WHERE u.email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.IsActive,
		&i.CreatedAt,
		&i.PublicKey,
		&i.PublicKeyFingerprint,
		&i.PublicKeyRegisteredAt,
		&i.PublicKeyExpiresAt,
		&i.MustChangePassword,
		&i.PasswordChangedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT u.id, u.name, u.email, u.password_hash, u.is_active, u.created_at,
       u.public_key, u.public_key_fingerprint, u.public_key_registered_at, u.public_key_expires_at,
       u.must_change_password, u.password_changed_at
FROM users u
WHERE u.id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.IsActive,
		&i.CreatedAt,
		&i.PublicKey,
		&i.PublicKeyFingerprint,
		&i.PublicKeyRegisteredAt,
		&i.PublicKeyExpiresAt,
		&i.MustChangePassword,
		&i.PasswordChangedAt,
	)
	return i, err
}

const getUserByPublicKeyFingerprint = `-- name: GetUserByPublicKeyFingerprint :one
SELECT u.id, u.name, u.email, u.public_key, u.public_key_fingerprint,
       u.public_key_registered_at, u.public_key_expires_at
FROM users u
WHERE u.public_key_fingerprint = $1
`

type GetUserByPublicKeyFingerprintRow struct {
	ID                    uuid.UUID          `json:"id"`
	Name                  string             `json:"name"`
	Email                 string             `json:"email"`
	PublicKey             *string            `json:"public_key"`
	PublicKeyFingerprint  *string            `json:"public_key_fingerprint"`
	PublicKeyRegisteredAt pgtype.Timestamptz `json:"public_key_registered_at"`
	PublicKeyExpiresAt    pgtype.Timestamptz `json:"public_key_expires_at"`
}

func (q *Queries) GetUserByPublicKeyFingerprint(ctx context.Context, publicKeyFingerprint *string) (GetUserByPublicKeyFingerprintRow, error) {
	row := q.db.QueryRow(ctx, getUserByPublicKeyFingerprint, publicKeyFingerprint)
	var i GetUserByPublicKeyFingerprintRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PublicKey,
		&i.PublicKeyFingerprint,
		&i.PublicKeyRegisteredAt,
		&i.PublicKeyExpiresAt,
	)
	return i, err
}

const getUsersWithExpiredPasswords = `-- name: GetUsersWithExpiredPasswords :many
SELECT id, name, email, password_changed_at, must_change_password, created_at
FROM users
WHERE is_active = true
  AND (
    must_change_password = true
    OR password_changed_at < NOW() - INTERVAL '90 days'
  )
`

type GetUsersWithExpiredPasswordsRow struct {
	ID                 uuid.UUID          `json:"id"`
	Name               string             `json:"name"`
	Email              string             `json:"email"`
	PasswordChangedAt  pgtype.Timestamptz `json:"password_changed_at"`
	MustChangePassword bool               `json:"must_change_password"`
	CreatedAt          time.Time          `json:"created_at"`
}

func (q *Queries) GetUsersWithExpiredPasswords(ctx context.Context) ([]GetUsersWithExpiredPasswordsRow, error) {
	rows, err := q.db.Query(ctx, getUsersWithExpiredPasswords)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUsersWithExpiredPasswordsRow{}
	for rows.Next() {
		var i GetUsersWithExpiredPasswordsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.PasswordChangedAt,
			&i.MustChangePassword,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsersWithExpiredPublicKeys = `-- name: GetUsersWithExpiredPublicKeys :many
SELECT id, name, email, public_key_fingerprint, public_key_registered_at, public_key_expires_at
FROM users
WHERE is_active = true
  AND (
    public_key_registered_at IS NULL
    OR public_key_expires_at < NOW()
  )
`

type GetUsersWithExpiredPublicKeysRow struct {
	ID                    uuid.UUID          `json:"id"`
	Name                  string             `json:"name"`
	Email                 string             `json:"email"`
	PublicKeyFingerprint  *string            `json:"public_key_fingerprint"`
	PublicKeyRegisteredAt pgtype.Timestamptz `json:"public_key_registered_at"`
	PublicKeyExpiresAt    pgtype.Timestamptz `json:"public_key_expires_at"`
}

func (q *Queries) GetUsersWithExpiredPublicKeys(ctx context.Context) ([]GetUsersWithExpiredPublicKeysRow, error) {
	rows, err := q.db.Query(ctx, getUsersWithExpiredPublicKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUsersWithExpiredPublicKeysRow{}
	for rows.Next() {
		var i GetUsersWithExpiredPublicKeysRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.PublicKeyFingerprint,
			&i.PublicKeyRegisteredAt,
			&i.PublicKeyExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT u.id, u.name, u.email, u.is_active, u.created_at,
       u.public_key_fingerprint, u.public_key_expires_at, u.must_change_password
FROM users u
ORDER BY u.created_at DESC
`

type ListUsersRow struct {
	ID                   uuid.UUID          `json:"id"`
	Name                 string             `json:"name"`
	Email                string             `json:"email"`
	IsActive             bool               `json:"is_active"`
	CreatedAt            time.Time          `json:"created_at"`
	PublicKeyFingerprint *string            `json:"public_key_fingerprint"`
	PublicKeyExpiresAt   pgtype.Timestamptz `json:"public_key_expires_at"`
	MustChangePassword   bool               `json:"must_change_password"`
}

func (q *Queries) ListUsers(ctx context.Context) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersRow{}
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.IsActive,
			&i.CreatedAt,
			&i.PublicKeyFingerprint,
			&i.PublicKeyExpiresAt,
			&i.MustChangePassword,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const registerPublicKey = `-- name: RegisterPublicKey :exec
UPDATE users
SET public_key = $2,
    public_key_fingerprint = $3,
    public_key_registered_at = NOW(),
    public_key_expires_at = NOW() + INTERVAL '90 days'
WHERE id = $1
`

type RegisterPublicKeyParams struct {
	ID                   uuid.UUID `json:"id"`
	PublicKey            *string   `json:"public_key"`
	PublicKeyFingerprint *string   `json:"public_key_fingerprint"`
}

func (q *Queries) RegisterPublicKey(ctx context.Context, arg RegisterPublicKeyParams) error {
	_, err := q.db.Exec(ctx, registerPublicKey, arg.ID, arg.PublicKey, arg.PublicKeyFingerprint)
	return err
}

const revokePublicKey = `-- name: RevokePublicKey :exec
UPDATE users
SET public_key = NULL,
    public_key_fingerprint = NULL,
    public_key_registered_at = NULL,
    public_key_expires_at = NULL
WHERE id = $1
`

func (q *Queries) RevokePublicKey(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokePublicKey, id)
	return err
}

const updatePassword = `-- name: UpdatePassword :exec
UPDATE users
SET password_hash = $2,
    must_change_password = false,
    password_changed_at = NOW()
WHERE id = $1
`

type UpdatePasswordParams struct {
	ID           uuid.UUID `json:"id"`
	PasswordHash string    `json:"password_hash"`
}

func (q *Queries) UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error {
	_, err := q.db.Exec(ctx, updatePassword, arg.ID, arg.PasswordHash)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET name = $2, email = $3
WHERE id = $1
RETURNING id, name, email, is_active, created_at, must_change_password, password_changed_at
`

type UpdateUserParams struct {
	ID    uuid.UUID `json:"id"`
	Name  string    `json:"name"`
	Email string    `json:"email"`
}

type UpdateUserRow struct {
	ID                 uuid.UUID          `json:"id"`
	Name               string             `json:"name"`
	Email              string             `json:"email"`
	IsActive           bool               `json:"is_active"`
	CreatedAt          time.Time          `json:"created_at"`
	MustChangePassword bool               `json:"must_change_password"`
	PasswordChangedAt  pgtype.Timestamptz `json:"password_changed_at"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error) {
	row := q.db.QueryRow(ctx, updateUser, arg.ID, arg.Name, arg.Email)
	var i UpdateUserRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.IsActive,
		&i.CreatedAt,
		&i.MustChangePassword,
		&i.PasswordChangedAt,
	)
	return i, err
}

const reactivateUser = `-- name: ReactivateUser :exec
UPDATE users SET is_active = true WHERE id = $1
`

func (q *Queries) ReactivateUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, reactivateUser, id)
	return err
}

const adminResetPassword = `-- name: AdminResetPassword :exec
UPDATE users
SET password_hash = $2,
    must_change_password = true,
    password_changed_at = NOW()
WHERE id = $1
`

type AdminResetPasswordParams struct {
	ID           uuid.UUID `json:"id"`
	PasswordHash string    `json:"password_hash"`
}

func (q *Queries) AdminResetPassword(ctx context.Context, arg AdminResetPasswordParams) error {
	_, err := q.db.Exec(ctx, adminResetPassword, arg.ID, arg.PasswordHash)
	return err
}
