// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_roles.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const assignRole = `-- name: AssignRole :one
INSERT INTO user_roles (user_id, role, assigned_by)
VALUES ($1, $2, $3)
RETURNING id, user_id, role, assigned_by, assigned_at
`

type AssignRoleParams struct {
	UserID     uuid.UUID `json:"user_id"`
	Role       string    `json:"role"`
	AssignedBy uuid.UUID `json:"assigned_by"`
}

func (q *Queries) AssignRole(ctx context.Context, arg AssignRoleParams) (UserRole, error) {
	row := q.db.QueryRow(ctx, assignRole, arg.UserID, arg.Role, arg.AssignedBy)
	var i UserRole
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Role,
		&i.AssignedBy,
		&i.AssignedAt,
	)
	return i, err
}

const deleteRolesByUserID = `-- name: DeleteRolesByUserID :exec
DELETE FROM user_roles WHERE user_id = $1
`

func (q *Queries) DeleteRolesByUserID(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteRolesByUserID, userID)
	return err
}

const getRolesByUserID = `-- name: GetRolesByUserID :many
SELECT ur.id, ur.user_id, ur.role, ur.assigned_by, ur.assigned_at
FROM user_roles ur
WHERE ur.user_id = $1
`

func (q *Queries) GetRolesByUserID(ctx context.Context, userID uuid.UUID) ([]UserRole, error) {
	rows, err := q.db.Query(ctx, getRolesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserRole{}
	for rows.Next() {
		var i UserRole
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Role,
			&i.AssignedBy,
			&i.AssignedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
